### ISSUE TITLE
[v3.9.2] Cached resource manager failed to clean up cached files

### ISSUE THREAD

**Issue by saphsara** [TheCSMods/mc-tcdcommons#11]
### What happened?

I am getting this error on my server in the console. is this part of you library or something else thx
[02:28:39] [tcdcommons:cachedresourcemanager/maid/ERROR]: Failed to clean up cached files;

### Steps to reproduce

Console

### Relevant log output or crash report

```shell
[02:28:39] [tcdcommons:cachedresourcemanager/maid/ERROR]: Failed to clean up cached files;
```

### Other installed mods

https://legacy.curseforge.com/minecraft/modpacks/saphsgaming/

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment]
Hello, and thank you for submitting a bug report!  
I have recently noticed this bug's existence as well, and it appears to take place when there are no cached files to clean up. So it's basically failing to clean up cache because there's no cache to begin with. I didn't check the code yet, but it's likely that I forgot to check if the cache exists first, before attempting to clean it up. Luckily other than appearing in the console, the error is completely harmless.  
I will likely look into resolving this in future updates. Thanks again, and have a great day!

**Comment by saphsara** [comment]
> Hello, and thank you for submitting a bug report! I have recently noticed this bug's existence as well, and it appears to take place when there are no cached files to clean up. So it's basically failing to clean up cache because there's no cache to begin with. I didn't check the code yet, but it's likely that I forgot to check if the cache exists first, before attempting to clean it up. Luckily other than appearing in the console, the error is completely harmless. I will likely look into resolving this in future updates. Thanks again, and have a great day!

Thank you for your fast response have a great day. No rush. I was just concerned.
