### ISSUE TITLE
Won't boot Minecraft

### ISSUE THREAD

**Issue by DavidFrings** [TheCSMods/mc-tcdcommons#12]
# Log
https://mclo.gs/hQSQqCj

# Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment]
Hello, I see you have closed the issue, likely because you found the solution or something.  
Either way, I will mention what I found in your crash report; The following line:
```
[16:51:24] [main/ERROR]: Mixin apply for mod shulkerboxtooltip failed shulkerboxtooltip-common.mixins.json:client.ShulkerBoxBlockMixin from mod shulkerboxtooltip -> net.minecraft.class_2480: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure:
```
This line shows that the issue likely has to do with a mod called `shulkerboxtooltip`. If the issue only takes place when TCDCommons API is installed however, then feel free to let me know, as in that case that could be an incompatibility (altho I do not believe there are any compatibility issues).

Thanks for wanting to reach out either way, and feel free to reach out again any time you need help.  
Have a great day!

**Comment by DavidFrings** [comment]
No my problem was Mouse Wheelie, but thx for your help
